image: alpine/edge
repositories: {}
environment:
 mirror: git@github.com:samuel-hunter/cl-gemini.git
 GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
secrets:
- d5d49965-cebb-4cfd-81ce-eefa5c8cdae7
shell: false
sources:
- https://git.sr.ht/~shunter/cl-gemini
tasks:
- updatemirror: |
    cd cl-gemini
    git remote add mirror $mirror
    git push mirror master
triggers: []
